language: go

go:
  - 1.12

go_import_path:
  - github.com/julienschmidt/httprouter
  - github.com/ma-null/NetInterface/handlers

before_install:
  - cp .netrc ~/.netrc
  - chmod 600 ~/.netrc

script:
  - go test -v ./...