language: go

go:
  - 1.12
  -
env:
  global:
    - IMAGE_NAME=manuller/netinterfaces
before_install:
  - cp .netrc ~/.netrc

install:
  - go get github.com/julienschmidt/httprouter
  - go get github.com/ma-null/NetInterface/handlers

script:
  - go test -v ./...
  - go build -v
  - docker build -t $IMAGE_NAME:$5 -t $IMAGE_NAME -f Dockerfile .
  - docker push $IMAGE_NAME
