language: go

go:
  - 1.12

before_install:
  - cp .netrc ~/.netrc
  - chmod 600 ~/.netrc\

install:
  - go get github.com/julienschmidt/httprouter
  - go get github.com/ma-null/NetInterface/handlers

script:
  - go test -v ./...